name: release_image

on:
  workflow_call:
    inputs:
      dockerhub_username:
        description: "Your dockerhub username. Defaults to the github repository owner."
        default: ${{ github.repository_owner }}
        type: string
      dockerhub_repository:
        description: "The dockerhub repository. Defaults to the github repository name."
        default: ${{ github.event.repository.name }}
        type: string

jobs:
  get_metadata:
    uses: spuxx1701/ci-cd/.github/workflows/release_image/get_metadata.yml@v2.0
    with:
      dockerhub_username: ${{ inputs.dockerhub_username }}
      dockerhub_repository: ${{ inputs.dockerhub_repository }}
