name: build_and_push_image

on:
  workflow_call:
    inputs:
      image_tags:
        description: "The image tags."
        type: string
        required: true
      dockerhub_username:
        description: "Your dockerhub username. Defaults to the github repository owner."
        default: ${{ github.repository_owner }}
        type: string
      dockerhub_repository:
        description: "The dockerhub repository. Defaults to the github repository name."
        default: ${{ github.event.repository.name }}
        type: string
      dockerfile:
        description: "The dockerfile path relative to the root folder. Defaults to 'Dockerfile'."
        default: Dockerfile
        type: string
    secrets:
      dockerhub_token:
        description: "The dockerhub access token."
        required: true

jobs:
  build_and_push_image:
    name: Build and push image to Dockerhub
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to DockerHub
        uses: docker/login-action@v2  
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./${{ inputs.dockerfile }}
          tags: ${{ inputs.image_tags }}
          
      - name: Finish
        shell: bash
        run: |
          echo "Image ${{ inputs.image_tags }} successfully build and pushed to Dockerhub."
