name: build_and_push_image

on:
  workflow_call:
    inputs:
      image_names:
        description: "The image name."
        type: string
        required: true
      platforms:
        description: "What platforms to build for."
        type: string
        default: "linux/amd64,linux/arm64"
      dockerhub_username:
        description: "Your dockerhub username. Defaults to 'spuxx'."
        default: spuxx
        type: string
      dockerhub_repository:
        description: "The dockerhub repository. Defaults to the github repository name."
        default: ${{ github.event.repository.name }}
        type: string
      dockerfile:
        description: "The dockerfile path relative to the root folder. Defaults to 'Dockerfile'."
        default: Dockerfile
        type: string
    secrets:
      dockerhub_token:
        description: "The dockerhub access token."
        required: true

jobs:
  build_and_push_image:
    name: Build and push image to Dockerhub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    timeout-minutes: 5
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ secrets.dockerhub_token }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        file: ./${{ inputs.dockerfile }}
        tags: ${{ inputs.image_names }}

    - name: Finish
      shell: bash
      run: |
        echo "Image ${{ inputs.image_tags }} successfully build and pushed to Dockerhub."
