name: get_metadata

on:
  workflow_call:
    inputs:
      dockerhub_username:
        description: "Your dockerhub username. Defaults to 'spuxx'."
        default: spuxx
        type: string
      dockerhub_repository:
        description: "The dockerhub repository. Defaults to the github repository name."
        default: ${{ github.event.repository.name }}
        type: string
    outputs:
      image_name:
        description: "The name of the image."
        value: ${{ jobs.get_metadata.outputs.image_name }}
      image_version:
        description: "The version of the image."
        value: ${{ jobs.get_metadata.outputs.image_version }}
      image_labels:
        description: "The image labels."
        value: ${{ jobs.get_metadata.outputs.image_labels }}

jobs:
  get_metadata:
    name: Get metadata for image and release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Prepare
        id: prep
        run: |
          echo "suffix=$SUFFIX" >> $GITHUB_OUTPUT
          SUFFIX="-$(date +'%Y%m%d-%H%M%S')-${{ github.sha }}"
          echo "suffix=$SUFFIX" >> $GITHUB_OUTPUT
          
      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.dockerhub_username }}/${{ inputs.dockerhub_repository }}
          tags: |
            type=ref,event=branch,suffix=${{ steps.prep.outputs.suffix }}
            type=semver,pattern={{version}}
            
      - name: Finish
        shell: bash
        run: |
          echo "Finished retrieving metadata."
          echo "Image name: ${{ steps.meta.outputs.tags }}"
          echo "Image version: ${{ steps.meta.outputs.version }}"
          echo "Image labels: ${{ steps.meta.outputs.labels }}"
            
    outputs:
      image_name: ${{ steps.meta.outputs.tags }}
      image_version: ${{ steps.meta.outputs.version }}
      image_labels: ${{ steps.meta.outputs.labels }}
