name: helm_release

on:
  workflow_call:
    inputs:
      charts_dir: 
        description: "The helm charts directory. Defaults to '/.helm'."
        default: '/.helm'
        type: string
      charts_repo:
        description: "The repository for publishing the helm charts. Defaults to 'helm-charts'."
        default: helm-charts
        type: string
      owner:
        description: "The owner of charts_repo. Defaults to the owner of the source repository."
        default: ${{ github.repository_owner }}
        type: string
    secrets:
      token:
        description: "The github access token for writing to charts_repo."
        required: true
      
jobs:
  helm_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.token }}
          charts_dir: ${{ inputs.charts_dir }}
          charts_url: https://{{ inputs.owner }}.github.io/${{ inputs.charts_repo }}
          owner: ${{ inputs.owner }}
          repository: ${{ inputs.charts_repo }}
          branch: gh-pages
