name: helm_release

on:
  workflow_call:
    inputs:
      charts_repo_url:
        description: "The URL of the charts repository. Defaults to '<github_repo_owner>.github.io/helm-charts'."
        default: ${{ github.repository_owner }}.github.io/helm-charts
        type: string
    secrets:
      token:
        description: "The github access token for CR."
        required: true
      
jobs:
  helm_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "${{ github.repository_owner }}"
          git config user.email "${{ github.repository_owner }}@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_GIT_REPO: helm-charts
          CR_TOKEN: "${{ secrets.token }}"
