name: npm_test

on:
  workflow_call:

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Install Browsers
        run: npx playwright install
      - name: Run Tests
        run: npm run test:ui
