name: Install dependencies and cache

on:
  workflow_call:
    inputs:
      PNPM_FLAGS:
        description: 'Flags to pass to pnpm commands (e.g. "-r --frozen-lockfile")'
        type: string
        required: false
        default: ''

jobs:
  install_deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        run_install: false

    - name: Install dependencies
      run: pnpm install ${{ inputs.PNPM_FLAGS }}

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-
