name: Run release-please

on:
  workflow_call:
    inputs:
      CONFIG_FILE_PATH:
        description: 'The path to the release-please configuration file'
        type: string
        required: false
        default: '.release-please/config.json'
      MANIFEST_FILE_PATH:
        description: 'The path to the release-please manifest file'
        type: string
        required: false
        default: '.release-please/manifest.json'
      ARGS:
        description: 'Further arguments that should be passed to release-please, see: https://github.com/googleapis/release-please/blob/main/docs/cli.md'
        type: string
        required: false
        default: ''
    secrets:
      TOKEN:
        description: "Token to authenticate with GitHub"
        required: true

jobs:
  run_release_please:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.PNPM_VERSION }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Create pull request
      run: |
        pnpx release-please ${{ inputs.ARGS }} release-pr \
        --repo-url=${{ github.repository_owner }}/${{ github.event.repository.name }} \
        --token=${{ secrets.TOKEN }} \
        --config-file=${{ inputs.CONFIG_FILE_PATH }} \
        --manifest-file=${{ inputs.MANIFEST_FILE_PATH }} \

    - name: Create GitHub release
      run: |
        pnpx release-please ${{ inputs.ARGS }} github-release \
        --repo-url=${{ github.repository_owner }}/${{ github.event.repository.name }} \
        --token=${{ secrets.TOKEN }} \
        --config-file=${{ inputs.CONFIG_FILE_PATH }} \
        --manifest-file=${{ inputs.MANIFEST_FILE_PATH }} \


