# For documentation, see: https://github.com/googleapis/release-please-action?tab=readme-ov-file#release-please-action
name: Run release-please

on:
  workflow_call:
    inputs:
      CONFIG_FILE_PATH:
        description: 'The path to the release-please configuration file'
        type: string
        required: false
        default: '.release-please/rp-config.json'
      MANIFEST_FILE_PATH:
        description: 'The path to the release-please manifest file'
        type: string
        required: false
        default: '.release-please/rp-manifest.json'
    secrets:
      TOKEN:
        description: "Token to authenticate with GitHub"
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  run_release_please:
    runs-on: ubuntu-latest
    steps:
    - uses: googleapis/release-please-action@v4
      with:
        token: ${{ secrets.TOKEN }}
        release-type: node
        config-file: ${{ inputs.CONFIG_FILE_PATH }}
        manifest-file: ${{ inputs.MANIFEST_FILE_PATH }}
