name: Build the project

on:
  workflow_call:
    inputs:
      PNPM_VERSION:
        description: 'The version of pnpm to use. Optional if packageManager is specified in package.json'
        type: string
        required: false
        default: ''
      PNPM_FLAGS:
        description: 'Flags to pass to pnpm commands (e.g. "-r --frozen-lockfile")'
        type: string
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.PNPM_VERSION }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Build
      run: pnpm ${{ inputs.PNPM_FLAGS }} build

    - name: Cache dist folder
      uses: actions/cache@v4
      with:
        path: dist
        key: dist
