name: Publish

on:
  workflow_call:
    inputs:
      PNPM_VERSION:
        description: 'The version of pnpm to use. Optional if packageManager is specified in package.json'
        type: string
        required: false
        default: ''
      PACKAGES_PATH:
        description: 'The path to where the packages are stored within the monorepo'
        type: string
        required: false
        default: 'packages'
    secrets:
      NPM_TOKEN:
        description: "Token to authenticate with npm registry"
        required: true

jobs:
  build_and_publish:
    name: Build and publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.PNPM_VERSION }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm -r install --frozen-lockfile

    - name: Build
      run: pnpm -r build

    - name: Setup .npmrc file
      run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Determine package name
      id: determine_package
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        PACKAGE_NAME=${TAG_NAME%-v*}
        echo "Determined package name: $PACKAGE_NAME"
        echo "package_name=${PACKAGE_NAME}" >> $GITHUB_OUTPUT

    - name: Merge package.json
      needs: determine_package
      run: |
        mv ${{ inputs.PACKAGES_PATH }}/${{ needs.determine_package.outputs.package_name }}/package.json ${{ inputs.PACKAGES_PATH }}/${{ needs.determine_package.outputs.package_name }}/package_template.json
        pnpx package-json-merge package.json ${{ inputs.PACKAGES_PATH }}/${{ needs.determine_package.outputs.package_name }}/package_template.json > ${{ inputs.PACKAGES_PATH }}/${{ needs.determine_package.outputs.package_name }}/package.json
        echo "package.json files were merged."

    - name: Publish to npm
      needs: determine_package
      run: |
        echo "Publishing as:"
        npm whoami
        echo "Publishing artifact(s)."
        pnpm -r publish --filter ${{ needs.determine_package.outputs.package_name }}"
 --no-git-checks --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

