name: Build the project

on:
  workflow_call:
    inputs:
      PNPM_FLAGS:
        description: 'Flags to pass to pnpm commands (e.g. "-r --frozen-lockfile")'
        type: string
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Retrieve cached node_modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node_modules

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        run_install: false

    - name: Build
      run: pnpm ${{ inputs.PNPM_FLAGS }} build

    - name: Cache dist folder
      uses: actions/cache@v4
      with:
        path: dist
        key: dist
