name: Build and publish package

on:
  workflow_call:
    inputs:
      PNPM_VERSION:
        description: 'The version of pnpm to use. Optional if packageManager is specified in package.json'
        type: string
        required: false
        default: ''
      PATH:
        description: "The path to the package's directory. Defaults to the project's root directory."
        type: string
        required: false
        default: '/'
      TAG:
        description: 'The tag under which to publish. Defaults to latest.'
        type: string
        required: false
        default: 'latest'
    secrets:
      NPM_TOKEN:
        description: "Token to authenticate with npm registry"
        required: true

jobs:
  build_and_publish:
    name: Build and publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.PNPM_VERSION }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Set working directory
      run: cd {{ inputs.PATH }}

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build
      run: pnpm build

    - name: Setup .npmrc file
      run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Publish to npm
      run: |
        echo "Publishing as:"
        npm whoami
        echo "Publishing artifact."
        pnpm publish --no-git-checks --access public --tag ${{ inputs.TAG }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

