name: Run checks

on:
  workflow_call:
    inputs:
      PNPM_VERSION:
        description: 'The version of pnpm to use. Optional if packageManager is specified in package.json'
        type: string
        required: false
        default: ''
      PNPM_BUILD:
        description: "Whether to run pnpm -r build before checks"
        type: boolean
        required: false
        default: false
      CHECK_COMMAND:
        description: "Command to run required checks like linting, formatting, etc."
        type: string
        required: false
        default: "check"

jobs:
  run_checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.PNPM_VERSION }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build packages
      if: ${{ inputs.PNPM_BUILD }}
      run: pnpm -r build

    - name: Run checks
      env:
        CHECK_COMMAND: ${{ inputs.CHECK_COMMAND }}
      run: pnpm run $CHECK_COMMAND
