name: Run checks

on:
  workflow_call:
    inputs:
      CHECK_COMMAND:
        description: "Command to run required checks like linting, formatting, etc."
        type: string
        required: false
        default: "check"

jobs:
  run_checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Retrieve cached node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Run checks
        run: pnpm check
