name: docker_deploy

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      repository:
        required: true
        type: string
      environment:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
    secrets:
      token:
        required: true
      ssh_host:
        required: true
      ssh_username:
        required: true
      ssh_password:
        required: true
    outputs:
      tags:
        description: "The dockerhub tags."
        value: ${{ jobs.docker_build_and_push.outputs.tags }}

jobs:
  build_and_push:
    name: Docker build and push
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: spuxx/${{inputs.repository}}:${{inputs.environment}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to DockerHub
        uses: docker/login-action@v2  
        with:
          username: ${{ inputs.username }}
          password: ${{ secrets.token }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./${{ inputs.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
