name: release_image

on:
  workflow_call:
    inputs:
      dockerhub_username:
        description: "Your dockerhub username. Defaults to 'spuxx'."
        default: spuxx
        type: string
      dockerhub_repository:
        description: "The dockerhub repository. Defaults to the github repository name."
        default: ${{ github.event.repository.name }}
        type: string
      dockerfile:
        description: "The dockerfile path relative to the root folder. Defaults to 'Dockerfile'."
        default: Dockerfile
        type: string
    secrets:
      dockerhub_token:
        description: "The dockerhub access token."
        required: true

jobs:
  get_metadata:
    uses: spuxx1701/ci-cd/.github/workflows/get_metadata.yml@v2.0
    with:
      dockerhub_username: ${{ inputs.dockerhub_username }}
      dockerhub_repository: ${{ inputs.dockerhub_repository }}
      
  build_and_push_image:
    needs:
      - get_metadata
    uses: spuxx1701/ci-cd/.github/workflows/build_and_push_image.yml@v2.0
    with:
      image_name: ${{ needs.get_metadata.outputs.image_name }}
      dockerhub_username: ${{ inputs.dockerhub_username }}
      dockerhub_repository: ${{ inputs.dockerhub_repository }}
      dockerfile: ${{ inputs.dockerfile }}
    secrets:
      dockerhub_token: ${{ secrets.dockerhub_token }}
